{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    { "expr": "sum(hashrate)" }
   ]
  },
  {
   "title": "Per-rig hashrate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    { "expr": "sum by (host) (hashrate)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "uptime", "legendFormat": "{{host}}" }
   ]
  }
 ]
}