{
 "title": "rig",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "192.168.1.100" }
  ]
 },
 "panels": [
  {
   "title": "Total hashrate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "sum(hashrate{host=\"$host\"})",
     "legendFormat": "Hashrate"
    }
   ]
  },
  {
   "title": "Per-GPU hashrate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "hashrate{host=\"$host\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "temperature{host=\"$host\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fan{host=\"$host\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(rejected{host=\"$host\"}[5m])",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "Hardware errors",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(hw{host=\"$host\"}[5m])",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(accepted{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "uptime{host=\"$host\"}"
    }
   ]
  }
 ]
}